apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wncp-backend-nex
  name: wncp-backend-nex
  # namespace: wncp-nex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wncp-backend-nex
  template:
    metadata:
      labels:
        app: wncp-backend-nex
    spec:
      containers:
      - name: cloud-portal-service
        image: wcp/cloud-portal-service:1.1 # dockerhub.globalwavenet.com/wcp/cloud-portal-service:1.1 #wcp/cloud-portal-service:1.1
        imagePullPolicy: Always
      imagePullSecrets:
      - name: nexusjen