apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "17"
  creationTimestamp: "2020-05-03T20:05:23Z"
  generation: 17
  labels:
    app: wncp-backend
  name: wncp-backend
  namespace: wncp-test-11
  resourceVersion: "7321690"
  selfLink: /apis/apps/v1/namespaces/wncp/deployments/wncp-backend
  uid: 6c6b759b-8d79-11ea-88ce-42010a8001f5
spec:
  minReadySeconds: 120
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wncp-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wncp-backend
    spec:
      containers:
      - image: gcr.io/wn-cloud-275704/cloud-portal-service@sha256:341e4bbc5188f655aa4d961027a340dfbf2c1cf5e9761c14a631730ad325521d
        imagePullPolicy: IfNotPresent
        name: cloud-portal-service-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30