apiVersion: v1
kind: Service
metadata:
  labels:
    app: wncp-fronend
  name: wncp-fronend-service
  namespace: wncp-test-11
spec:
  # clusterIP: 10.0.0.1
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32625
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: wncp-fronend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
