apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: "2020-05-03T20:17:15Z"
  generation: 9
  labels:
    app: wncp-fronend
  name: wncp-fronend
  namespace: wncp
  resourceVersion: "4208175"
  selfLink: /apis/apps/v1/namespaces/wncp/deployments/wncp-fronend
  uid: 14b58c65-8d7b-11ea-88ce-42010a8001f5
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wncp-fronend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wncp-fronend
    spec:
      containers:
      - image: gcr.io/wn-cloud-275704/cloud-portal-frontend@sha256:a43821b760dbb883e089f55c12b2a5553f4017bc812f733a1403452402026134
        imagePullPolicy: IfNotPresent
        name: cloud-portal-frontend-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-05-03T20:17:18Z"
    lastUpdateTime: "2020-05-03T20:17:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-05-03T20:17:15Z"
    lastUpdateTime: "2020-05-13T05:12:47Z"
    message: ReplicaSet "wncp-fronend-68dd76cdfb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 9
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
